# Generated by Django 2.1.2 on 2019-02-07 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0003_auto_20190207_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='musician',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='musicians.Musician'),
        ),
    ]
