# Generated by Django 2.1.2 on 2019-03-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0004_auto_20190207_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
