# Generated by Django 2.1.2 on 2019-02-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('musician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='musicians.Musician')),
            ],
        ),
    ]
