# Generated by Django 2.1.2 on 2019-03-30 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('singer', models.CharField(default='', max_length=100)),
                ('year', models.IntegerField(default=1900)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Genre')),
            ],
        ),
    ]
