# Generated by Django 2.1.2 on 2019-03-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='hearts',
            field=models.IntegerField(default=0),
        ),
    ]
